export const GET_COINS_AND_WALLET_AMOUNT = 'GET_COINS_AND_WALLET_AMOUNT';
export const INSERT_COIN = 'INSERT_COIN';
export const SET_IS_DRAGGING_COIN = 'SET_IS_DRAGGING_COIN';
export const SET_IS_COIN_DROPZONE = 'SET_IS_COIN_DROPZONE';
export const SET_COIN_ERROR = 'SET_COIN_ERROR';
export const UPDATE_INSERTED_COIN_AMOUNT = 'UPDATE_INSERTED_COIN_AMOUNT';
export const COLLECT_COIN_REFUND = 'COLLECT_COIN_REFUND';
export const REFILL_COINS_QUANTITY = 'REFILL_COINS_QUANTITY';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const UPDATE_PRODUCT_STOCK = 'UPDATE_PRODUCT_STOCK';
export const COLLECT_PRODUCT = 'COLLECT_PRODUCT';
export const SET_IS_PRODUCT_COLLECTED = 'SET_IS_PRODUCT_COLLECTED';
export const REFILL_PRODUCT_STOCK_QUANTITY = 'REFILL_PRODUCT_STOCK_QUANTITY';
