export const INSERT_COIN = 'INSERT_COIN';
export const SET_IS_DRAGGING_COIN = 'SET_IS_DRAGGING_COIN';
export const SET_IS_COIN_DROPZONE = 'SET_IS_COIN_DROPZONE';
export const UPDATE_INSERTED_COIN_AMOUNT = 'UPDATE_INSERTED_COIN_AMOUNT';
export const SET_COIN_ERROR = 'SET_COIN_ERROR';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const UPDATE_PRODUCT_STOCK = 'UPDATE_PRODUCT_STOCK';
