export const INSERT_COIN = 'INSERT_COIN';
export const SET_IS_DRAGGING_COIN = 'SET_IS_DRAGGING_COIN';
export const SET_IS_COIN_DROPZONE = 'SET_IS_COIN_DROPZONE';
export const SET_COIN_ERROR = 'SET_COIN_ERROR';
